#!/usr/bin/env ruby

require './teacher'
require './student'
require './book'
require './rental'

$people = []
$books = []

def add_book
  print 'Title: '
  title = gets
  print 'Author: '
  author = gets
  book = Book.new(title, author)
  $books.push(book)
  puts 'Book created successfully'
end

def show_books
  $books.each { |book| print "Title: #{book.title.chomp}, Author: #{book.author}" }
end

def get_book
  puts 'Select a book from the following list by number'
  $books.each_with_index { |book, index| print "#{index}) Title: #{book.title.chomp}, Author: #{book.author}" }
  gets.chomp.to_i
end

def add_person(person)
  $people.push(person)
  puts 'Person created successfully'
end

def show_people
  $people.each do |person|
    if person.instance_of? Student
      print "[Student] Name: #{person.name.chomp}, ID: #{person.id.to_s.chomp}, Age: #{person.age}"
    else
      print "[Teacher] Name: #{person.name.chomp}, ID: #{person.id.to_s.chomp}, Age: #{person.age}"
    end
  end
end

def get_person
  puts 'Select a prson from the following list by number (not id)'
  $people.each_with_index do |person, index|
    if person.instance_of? Student
      print "#{index}) [Student] Name: #{person.name.chomp}, ID: #{person.id.to_s.chomp}, Age: #{person.age}"
    else
      print "#{index}) [Teacher] Name: #{person.name.chomp}, ID: #{person.id.to_s.chomp}, Age: #{person.age}"
    end
  end
  gets.chomp.to_i
end

def person_options(number)
  case number
  when 1
    print 'Age: '
    age = gets
    print 'Name: '
    name = gets
    print 'Has parent permission? [Y/N]: '
    parent = gets.chomp
    if parent == 'y' || parent == 'Y'
      student = Student.new(age, name)
      add_person(student)
    elsif parent == 'n' || parent == 'N'
      student = Student.new(age, name, false)
      add_person(student)
    else
      puts 'Please only use (Y) or (N) options'
    end
  when 2
    print 'Age: '
    age = gets
    print 'Name: '
    name = gets
    print 'Specialization: '
    specialization = gets
    teacher = Teacher.new(age, specialization, name)
    add_person(teacher)
  else
    puts 'Please input a (1) or a (2) only'
  end
end

def create_rental
 iBook = get_book
 iPerson = get_person
 print 'Date: '
 date = gets.chomp
 Rental.new(date, $books[iBook], $people[iPerson])
end

def general_options(number)
  case number
  when 1
    show_books
  when 2
    show_people
  when 3
    print 'Do you want to create a student (1) or a teacher (2)? [Input the number]'
    person_options(gets.chomp.to_i)
  when 4
    add_book
  when 5
    create_rental
  when 6
  when 7
    puts 'Goodbye'
  else
    puts "\n\nPlease select an option (1 - 7)"
  end
end

def main
  number = 1
  while (number != 7)
    puts "\n\nWelcome to School Library App!\n\n"
    puts 'Please choose an option by entering a number: '
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for a given person id'
    puts '7 - Exit'
    number = gets.chomp.to_i
    general_options(number)
  end
end

main()
